ktor:
    application:
        modules:
            - com.janteadebowale.ApplicationKt.module
    deployment:
        port: 8080
jwt:
  domain: "https://janteadebowale.com/"
  issuer: "https://janteadebowale.com/"
  audience: "mobile-application"
  realm: "ktor Jwt Auth"

